name: PR checks
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  PR-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: npm run lint
      - run: npm run build-ts
      - run: npm run test
