name: PR checks
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  PR-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - run: yarn run lint
      - run: yarn run build-ts
      - run: yarn run test
